"""
Junior Agent Layer — 383 Junior Execution Agents.
Structured executors. They follow precise instructions.
No strategic decisions. High throughput, low cost (Haiku).
"""
import json, logging, re
from backend.orchestration.base_agent import BaseAgent
from backend.orchestration.protocol import Task, AgentTier, AutonomyLevel

logger = logging.getLogger(__name__)


class JuniorAgent(BaseAgent):
    AGENT_TIER           = AgentTier.JUNIOR
    AUTONOMY_LEVEL       = AutonomyLevel.L3_AI_EXECUTES_AUDIT
    CONFIDENCE_THRESHOLD = 0.65
    ESCALATE_TO_TYPE     = "snr_generic"
    MODEL                = "claude-haiku-4-5-20251001"
    MAX_TOKENS           = 1500

    async def _reason(self, task: Task, context: dict) -> tuple[dict, float, list[str]]:
        trace = [f"[{self.agent_id}] Executing: {task.title}"]
        prompt = f"""Role: {self.SYSTEM_PROMPT}
Task: {task.title}
Instructions: {task.description}
Context: {json.dumps(context, default=str)[:1200]}

Execute this task precisely. Return JSON:
{"output": "...", "status": "completed|partial|failed", "notes": "...", "confidence": 0.0}
JSON only."""
        resp, conf = await self._llm(prompt)
        try:
            result = json.loads(resp)
        except Exception:
            result = {"output": resp[:600], "status": "partial", "parse_error": True}
            conf *= 0.6
        return result, result.get("confidence", conf), trace


def create_junior_class(type_key, dept, responsibility):
    return type(
        f"Junior_{type_key}",
        (JuniorAgent,),
        {
            "AGENT_ID_PREFIX": type_key,
            "AGENT_TYPE_KEY":  type_key,
            "DEPARTMENT":      dept,
            "SYSTEM_PROMPT":   f"Junior specialist: {responsibility}",
        }
    )

_JUNIOR_DEFINITIONS = [
    ("jnr_reg_india_rbi", "operations", "Crawl and parse RBI regulatory publications and circulars"),
    ("jnr_reg_india_sebi", "operations", "Crawl SEBI regulations: LODR, ICDR, insider trading"),
    ("jnr_reg_india_irdai", "operations", "Crawl IRDAI insurance regulations and circulars"),
    ("jnr_reg_india_pfrda", "operations", "Crawl PFRDA pension fund regulations"),
    ("jnr_reg_india_fiu", "operations", "Crawl FIU-IND AML/CFT notifications"),
    ("jnr_reg_india_mca", "operations", "Crawl MCA Companies Act notifications"),
    ("jnr_reg_india_cert", "operations", "Crawl CERT-In cybersecurity directives"),
    ("jnr_reg_india_meity", "operations", "Crawl MEITY IT Act amendments and rules"),
    ("jnr_reg_uk_fca", "operations", "Crawl FCA policy statements, supervisory statements, consults"),
    ("jnr_reg_uk_pra", "operations", "Crawl PRA rules, supervisory statements, Dear CEO letters"),
    ("jnr_reg_uk_ico", "operations", "Crawl ICO data protection guidance and enforcement notices"),
    ("jnr_reg_uk_bo", "operations", "Crawl Bank of England financial stability publications"),
    ("jnr_reg_uk_cma", "operations", "Crawl CMA competition and merger decisions"),
    ("jnr_reg_uk_pso", "operations", "Crawl PSO/PSR payment systems regulation"),
    ("jnr_reg_eu_eba", "operations", "Crawl EBA guidelines, opinions, binding technical standards"),
    ("jnr_reg_eu_esma", "operations", "Crawl ESMA regulations: EMIR, MiFID2, CSDR"),
    ("jnr_reg_eu_eiopa", "operations", "Crawl EIOPA insurance regulations"),
    ("jnr_reg_eu_ecb", "operations", "Crawl ECB supervisory publications for significant banks"),
    ("jnr_reg_eu_edps", "operations", "Crawl EDPS data protection opinions"),
    ("jnr_reg_eu_enisa", "operations", "Crawl ENISA cybersecurity guidance, DORA implementation"),
    ("jnr_reg_us_fed", "operations", "Crawl Federal Reserve regulations: SR letters, CBCA"),
    ("jnr_reg_us_occ", "operations", "Crawl OCC interpretive letters, comptroller handbook"),
    ("jnr_reg_us_fdic", "operations", "Crawl FDIC financial institution letters and rulings"),
    ("jnr_reg_us_cfpb", "operations", "Crawl CFPB rules: TILA, RESPA, fair lending"),
    ("jnr_reg_us_sec", "operations", "Crawl SEC rules and releases"),
    ("jnr_reg_us_cftc", "operations", "Crawl CFTC swap dealer regulations, position limits"),
    ("jnr_reg_us_fincen", "operations", "Crawl FinCEN AML/BSA rulemaking and guidance"),
    ("jnr_reg_us_fatf", "operations", "Crawl FATF recommendations and mutual evaluation reports"),
    ("jnr_reg_sg_mas", "operations", "Crawl MAS circulars, notices, guidelines"),
    ("jnr_reg_sg_pdpc", "operations", "Crawl PDPC Personal Data Protection Act guidance"),
    ("jnr_reg_au_apra", "operations", "Crawl APRA prudential standards and guidance notes"),
    ("jnr_reg_au_asic", "operations", "Crawl ASIC regulatory guides and market integrity rules"),
    ("jnr_reg_au_oaic", "operations", "Crawl OAIC privacy guidance and determinations"),
    ("jnr_reg_hk_hkma", "operations", "Crawl HKMA circular and supervisory policy manuals"),
    ("jnr_reg_hk_sfc", "operations", "Crawl SFC Hong Kong licensing and code revisions"),
    ("jnr_reg_jp_fsa", "operations", "Crawl Japan FSA supervisory guidelines"),
    ("jnr_reg_ca_osfi", "operations", "Crawl OSFI Canada prudential guidelines"),
    ("jnr_reg_za_sarb", "operations", "Crawl SARB South Africa banking regulations"),
    ("jnr_reg_br_bcb", "operations", "Crawl BCB Brazil central bank regulations"),
    ("jnr_reg_ae_cbuae", "operations", "Crawl CBUAE UAE central bank regulations"),
    ("jnr_reg_ke_cma", "operations", "Crawl Kenya CMA capital market regulations"),
    ("jnr_reg_ng_cbn", "operations", "Crawl CBN Nigeria central bank guidelines"),
    ("jnr_reg_ph_bsp", "operations", "Crawl BSP Philippines central bank circulars"),
    ("jnr_reg_id_ojk", "operations", "Crawl OJK Indonesia financial services regulations"),
    ("jnr_reg_th_bot", "operations", "Crawl Bank of Thailand guidelines and notifications"),
    ("jnr_reg_my_bnm", "operations", "Crawl BNM Malaysia central bank policy documents"),
    ("jnr_reg_lk_cbsl", "operations", "Crawl CBSL Sri Lanka central bank circulars"),
    ("jnr_reg_pk_sbp", "operations", "Crawl SBP Pakistan central bank regulations"),
    ("jnr_reg_bd_bb", "operations", "Crawl Bangladesh Bank regulatory circulars"),
    ("jnr_reg_global_bis", "operations", "Crawl BIS Basel Committee publications and standards"),
    ("jnr_reg_global_fatf2", "operations", "Crawl FATF typology reports and guidance papers"),
    ("jnr_reg_global_iosco", "operations", "Crawl IOSCO principles and methodology documents"),
    ("jnr_reg_global_fsb", "operations", "Crawl FSB recommendations and progress reports"),
    ("jnr_reg_global_iasb", "operations", "Crawl IASB IFRS standards and exposure drafts"),
    ("jnr_reg_eu_aica", "operations", "Crawl EU AI Act implementation guidance and guidelines"),
    ("jnr_reg_eu_mica", "operations", "Crawl EU MiCA crypto asset regulation guidance"),
    ("jnr_reg_eu_dora", "operations", "Crawl DORA digital resilience implementation RTSs"),
    ("jnr_reg_eu_psd3", "operations", "Crawl EU PSD3 and PSR legislative progress"),
    ("jnr_reg_eu_fida", "operations", "Crawl EU FIDA open finance regulation progress"),
    ("jnr_reg_eu_gdpr2", "operations", "Crawl GDPR enforcement actions and DPA guidance"),
    ("jnr_reg_eu_ctf", "operations", "Crawl EU 6th AML Directive and AMLA regulations"),
    ("jnr_reg_us_ai", "operations", "Crawl US AI executive orders and OAI guidance"),
    ("jnr_reg_uk_ai", "operations", "Crawl UK AI regulation white paper updates"),
    ("jnr_reg_in_ais", "operations", "Crawl India AI governance framework"),
    ("jnr_reg_eu_esg", "operations", "Crawl EU CSRD, SFDR, taxonomy regulation updates"),
    ("jnr_reg_us_esg", "operations", "Crawl SEC climate disclosure rules and ESG guidance"),
    ("jnr_reg_global_cbdc", "operations", "Crawl central bank digital currency regulatory guidance"),
    ("jnr_reg_global_stables", "operations", "Crawl stablecoin regulatory frameworks globally"),
    ("jnr_reg_global_defi", "operations", "Crawl DeFi regulatory guidance across jurisdictions"),
    ("jnr_reg_global_open", "operations", "Crawl open banking/open finance global developments"),
    ("jnr_reg_global_cloud", "operations", "Crawl cloud outsourcing regulations for financial services"),
    ("jnr_reg_global_cyber", "operations", "Crawl financial sector cybersecurity regulations globally"),
    ("jnr_reg_global_op_risk", "operations", "Crawl Basel operational risk framework implementations"),
    ("jnr_reg_global_climate", "operations", "Crawl climate-related financial risk regulatory guidance"),
    ("jnr_reg_eu_crypto", "operations", "Crawl EU crypto-asset regulation: TFR, CASP licensing"),
    ("jnr_reg_us_crypto", "operations", "Crawl US crypto regulatory: SAB 121, broker rules"),
    ("jnr_reg_uk_crypto", "operations", "Crawl UK FCA crypto promotion, CASP registration"),
    ("jnr_reg_sg_crypto", "operations", "Crawl MAS digital token payment services licensing"),
    ("jnr_tech_bug_fixer", "technology", "Fix identified bugs in FastAPI backend codebase"),
    ("jnr_tech_test_runner", "technology", "Execute automated test suites, report failures"),
    ("jnr_tech_deploy_verifier", "technology", "Verify deployment health checks and smoke tests"),
    ("jnr_tech_log_analyzer", "technology", "Analyze application logs for errors and anomalies"),
    ("jnr_tech_perf_profiler", "technology", "Profile application performance, identify slow paths"),
    ("jnr_tech_db_migrator", "technology", "Execute database migration scripts, verify success"),
    ("jnr_tech_api_tester", "technology", "Execute API endpoint tests, verify response contracts"),
    ("jnr_tech_cache_warmer", "technology", "Pre-warm Redis cache with frequently accessed data"),
    ("jnr_tech_search_indexer", "technology", "Rebuild and update full-text search indexes"),
    ("jnr_tech_s3_organizer", "technology", "Organize and tag S3 objects, apply lifecycle policies"),
    ("jnr_tech_secret_rotator", "technology", "Rotate API keys and secrets on schedule"),
    ("jnr_tech_cert_checker", "technology", "Check SSL certificate expiry, alert on upcoming renewal"),
    ("jnr_tech_backup_verifier", "technology", "Verify database backup integrity, test restore"),
    ("jnr_tech_disk_cleaner", "technology", "Clean up temporary files, old logs, expired data"),
    ("jnr_tech_metrics_tagger", "technology", "Tag infrastructure metrics for cost allocation"),
    ("jnr_tech_health_pinger", "technology", "Ping all service endpoints, verify health responses"),
    ("jnr_tech_jwt_validator", "technology", "Validate JWT token handling and expiry behavior"),
    ("jnr_tech_rate_enforcer", "technology", "Verify rate limiting is working correctly per plan"),
    ("jnr_tech_webhook_tester", "technology", "Test Stripe and other webhook signature verification"),
    ("jnr_tech_email_tester", "technology", "Test SendGrid email delivery, template rendering"),
    ("jnr_tech_push_tester", "technology", "Test Expo push notification delivery to test devices"),
    ("jnr_tech_mobile_tester", "technology", "Execute React Native test suite, E2E mobile tests"),
    ("jnr_tech_a11y_tester", "technology", "Automated accessibility test execution, WAVE/axe"),
    ("jnr_tech_seo_crawler", "technology", "Crawl own site for SEO issues, broken links, missing tags"),
    ("jnr_tech_schema_gen", "technology", "Generate/update JSON Schema and OpenAPI specs"),
    ("jnr_tech_mock_generator", "technology", "Generate mock data for development and testing"),
    ("jnr_tech_code_linter", "technology", "Run linters: ruff, mypy, eslint, identify violations"),
    ("jnr_tech_dep_updater", "technology", "Check for dependency updates, security patch notes"),
    ("jnr_tech_docker_scanner", "technology", "Scan Docker images for CVEs using Trivy/Grype"),
    ("jnr_tech_port_scanner", "technology", "Scan for unexpected open ports, report anomalies"),
    ("jnr_tech_sql_checker", "technology", "Check for N+1 queries, missing indexes, slow queries"),
    ("jnr_tech_memory_profiler", "technology", "Profile Python memory usage, detect memory leaks"),
    ("jnr_tech_token_counter", "technology", "Count and track Anthropic API token usage by agent"),
    ("jnr_tech_cost_tracker", "technology", "Track and report AWS/API costs in real-time"),
    ("jnr_tech_uptime_monitor", "technology", "Monitor external uptime, track SLA compliance"),
    ("jnr_tech_dns_checker", "technology", "Verify DNS records, propagation, DKIM/SPF/DMARC"),
    ("jnr_tech_cors_tester", "technology", "Test CORS headers, verify allowed origins"),
    ("jnr_tech_csrf_tester", "technology", "Test CSRF protection on authenticated endpoints"),
    ("jnr_tech_xss_tester", "technology", "Test for XSS vulnerabilities in frontend pages"),
    ("jnr_tech_injection_tester", "technology", "Test for SQL/NoSQL injection vulnerabilities"),
    ("jnr_tech_config_auditor", "technology", "Audit environment variables and config for exposed secrets"),
    ("jnr_tech_log_shipper", "technology", "Ship application logs to centralized logging system"),
    ("jnr_tech_trace_collector", "technology", "Collect distributed traces for latency analysis"),
    ("jnr_tech_alert_router", "technology", "Route monitoring alerts to correct Slack channels"),
    ("jnr_tech_changelogs", "technology", "Generate changelog entries from git commits"),
    ("jnr_tech_coverage_check", "technology", "Run test coverage reports, flag under-covered code"),
    ("jnr_tech_bundle_analyzer", "technology", "Analyze JS bundle size, flag large dependencies"),
    ("jnr_tech_image_optimizer", "technology", "Optimize images for web delivery, convert to WebP"),
    ("jnr_tech_font_loader", "technology", "Optimize font loading, subset fonts, WOFF2 conversion"),
    ("jnr_tech_sitemap_gen", "technology", "Generate and update XML sitemap for all alert pages"),
    ("jnr_tech_robots_mgr", "technology", "Manage robots.txt, crawl rate limits, noindex rules"),
    ("jnr_tech_og_tagger", "technology", "Verify and update Open Graph meta tags on all pages"),
    ("jnr_tech_structured_data", "technology", "Implement and verify JSON-LD structured data on pages"),
    ("jnr_tech_cr_lab", "technology", "Run Lighthouse/CrUX lab tests, track Core Web Vitals"),
    ("jnr_tech_build_optimizer", "technology", "Optimize Docker build times, layer caching"),
    ("jnr_tech_env_parity", "technology", "Verify dev/staging/production environment parity"),
    ("jnr_tech_feature_flag", "technology", "Manage feature flags for staged rollouts"),
    ("jnr_tech_ab_runner", "technology", "Execute A/B test assignment and tracking"),
    ("jnr_tech_event_tracker", "technology", "Verify product analytics event tracking completeness"),
    ("jnr_tech_session_recorder", "technology", "Monitor session recording quality and completeness"),
    ("jnr_tech_error_tracker", "technology", "Monitor Sentry error rates, group similar errors"),
    ("jnr_tech_release_noter", "technology", "Generate release notes from PR descriptions"),
    ("jnr_tech_version_bumper", "technology", "Bump semantic versions in package manifests"),
    ("jnr_tech_tag_creator", "technology", "Create git tags for releases, trigger deploy pipelines"),
    ("jnr_tech_infra_tagger", "technology", "Apply cost allocation tags to all AWS resources"),
    ("jnr_tech_ri_analyzer", "technology", "Analyze Reserved Instance coverage, savings opportunities"),
    ("jnr_tech_spot_manager", "technology", "Manage Spot Instance interruption handling"),
    ("jnr_tech_autoscale_tuner", "technology", "Tune ECS autoscaling parameters based on load patterns"),
    ("jnr_tech_connection_pool", "technology", "Monitor and tune database connection pool settings"),
    ("jnr_tech_redis_mem_mgr", "technology", "Monitor Redis memory usage, eviction policies"),
    ("jnr_tech_pg_vacuum", "technology", "Manage PostgreSQL autovacuum settings and execution"),
    ("jnr_tech_index_builder", "technology", "Build new database indexes concurrently without locks"),
    ("jnr_tech_partition_mgr", "technology", "Manage time-series table partitioning for alert history"),
    ("jnr_tech_replication_mon", "technology", "Monitor PostgreSQL replication lag, failover readiness"),
    ("jnr_tech_ssl_renewer", "technology", "Automate Let's Encrypt SSL certificate renewal"),
    ("jnr_tech_waf_updater", "technology", "Update WAF rules to block emerging attack patterns"),
    ("jnr_tech_ip_blocker", "technology", "Block malicious IP ranges from rate limit violations"),
    ("jnr_prod_alert_writer", "product", "Draft regulatory alert summaries from parsed source docs"),
    ("jnr_prod_title_gen", "product", "Generate concise, SEO-friendly alert titles"),
    ("jnr_prod_tag_assigner", "product", "Assign topic tags and sector tags to alerts"),
    ("jnr_prod_sev_scorer", "product", "Score alert severity: critical/high/medium/info"),
    ("jnr_prod_impact_scorer", "product", "Calculate base impact score 0-10 for each alert"),
    ("jnr_prod_deadline_extractor", "product", "Extract regulatory deadlines from alert source documents"),
    ("jnr_prod_sector_tagger", "product", "Tag affected business sectors for each alert"),
    ("jnr_prod_juris_mapper", "product", "Map each alert to correct jurisdiction codes"),
    ("jnr_prod_reg_tagger", "product", "Tag regulatory body name and abbreviation"),
    ("jnr_prod_related_finder", "product", "Find related historical alerts for cross-reference"),
    ("jnr_prod_seo_meta", "product", "Generate SEO meta title and description for alert pages"),
    ("jnr_prod_schema_markup", "product", "Generate structured data schema for alert pages"),
    ("jnr_prod_og_image", "product", "Generate Open Graph image metadata for alert sharing"),
    ("jnr_prod_link_extractor", "product", "Extract and verify source document URLs"),
    ("jnr_prod_date_normalizer", "product", "Normalize all dates to ISO 8601 across jurisdictions"),
    ("jnr_prod_currency_norm", "product", "Normalize all monetary thresholds to standard format"),
    ("jnr_prod_entity_extractor", "product", "Extract named entities: companies, regulators, products"),
    ("jnr_prod_keyword_extractor", "product", "Extract key regulatory terms and definitions"),
    ("jnr_prod_summary_grader", "product", "Grade summary quality: clarity, accuracy, completeness"),
    ("jnr_prod_readability", "product", "Assess and improve readability of regulatory summaries"),
    ("jnr_prod_intel_writer", "product", "Draft consulting/bank intelligence synthesis summaries"),
    ("jnr_prod_firm_tagger", "product", "Tag intelligence items with source firm names"),
    ("jnr_prod_report_drafter", "product", "Draft sections of monthly intelligence reports"),
    ("jnr_prod_report_formatter", "product", "Format monthly reports to PDF-ready structure"),
    ("jnr_prod_trend_writer", "product", "Write trending topic summaries and analysis"),
    ("jnr_prod_digest_writer", "product", "Assemble weekly email digest content"),
    ("jnr_prod_alert_dedup", "product", "Identify duplicate alerts from overlapping sources"),
    ("jnr_prod_urgency_tagger", "product", "Tag alerts with urgency level for push notification"),
    ("jnr_prod_action_extractor", "product", "Extract recommended compliance actions from alerts"),
    ("jnr_prod_gap_analyzer", "product", "Analyze policy gaps against new regulatory requirements"),
    ("jnr_prod_health_scorer", "product", "Calculate client compliance health score updates"),
    ("jnr_prod_cascade_predictor", "product", "Predict cascade effects of regulation on other markets"),
    ("jnr_prod_timeline_builder", "product", "Build regulatory implementation timeline from sources"),
    ("jnr_prod_comparison", "product", "Compare new regulation to previous version"),
    ("jnr_prod_faq_generator", "product", "Generate FAQ section for complex regulatory alerts"),
    ("jnr_prod_glossary_updater", "product", "Update regulatory glossary with new terms"),
    ("jnr_prod_citation_generator", "product", "Generate regulatory citation in multiple formats"),
    ("jnr_prod_content_refresher", "product", "Refresh stale alert content when regulation is updated"),
    ("jnr_prod_translation_prep", "product", "Prepare content for translation, mark technical terms"),
    ("jnr_prod_localization", "product", "Localize date formats, currency symbols, regulatory names"),
    ("jnr_prod_feature_requester", "product", "Log and categorize user feature requests"),
    ("jnr_prod_user_feedback", "product", "Process and categorize user feedback submissions"),
    ("jnr_prod_nps_writer", "product", "Write NPS survey follow-up templates"),
    ("jnr_prod_ux_issue_logger", "product", "Log UI/UX issues found in user sessions"),
    ("jnr_prod_copy_writer", "product", "Write UI copy: buttons, tooltips, empty states, errors"),
    ("jnr_prod_email_templ", "product", "Design and write product email templates"),
    ("jnr_prod_push_copy", "product", "Write push notification copy for regulatory alerts"),
    ("jnr_prod_help_article", "product", "Write help centre articles for product features"),
    ("jnr_prod_changelog_writer", "product", "Write user-facing changelog entries"),
    ("jnr_prod_pricing_copy", "product", "Write and A/B test pricing page copy"),
    ("jnr_prod_onboarding_copy", "product", "Write onboarding flow copy and tooltips"),
    ("jnr_prod_cta_writer", "product", "Write and test call-to-action copy variations"),
    ("jnr_prod_persona_updater", "product", "Update user persona documents from research data"),
    ("jnr_prod_journey_mapper", "product", "Map user journey touchpoints from session data"),
    ("jnr_prod_heatmap_analyzer", "product", "Analyze page heatmaps, identify dead zones"),
    ("jnr_prod_session_reviewer", "product", "Review recorded user sessions for UX issues"),
    ("jnr_prod_survey_creator", "product", "Create targeted user research surveys"),
    ("jnr_prod_card_sorter", "product", "Conduct information architecture card sort analysis"),
    ("jnr_prod_prototype_reviewer", "product", "Review interactive prototypes against specs"),
    ("jnr_prod_component_doc", "product", "Document UI components in design system"),
    ("jnr_prod_icon_requester", "product", "Request and spec new icons for design system"),
    ("jnr_prod_competitor_spy", "product", "Monitor competitor product changes and new features"),
    ("jnr_prod_review_collector", "product", "Collect and categorize App Store/Play Store reviews"),
    ("jnr_prod_abn_tester", "product", "Set up and monitor A/B tests in product"),
    ("jnr_prod_experiment_doc", "product", "Document experiment results and learnings"),
    ("jnr_prod_cohort_reporter", "product", "Generate cohort retention reports"),
    ("jnr_prod_dau_reporter", "product", "Report daily/monthly active user metrics"),
    ("jnr_prod_engagement_reporter", "product", "Report feature engagement and adoption rates"),
    ("jnr_prod_api_usage_reporter", "product", "Report API usage by partner and endpoint"),
    ("jnr_prod_rev_reporter", "product", "Report MRR, ARR, churn rate, expansion revenue"),
    ("jnr_prod_conversion_reporter", "product", "Report conversion rates at each funnel stage"),
    ("jnr_prod_support_reporter", "product", "Report support ticket volume and resolution times"),
    ("jnr_prod_quality_reporter", "product", "Report alert quality scores and validation pass rates"),
    ("jnr_prod_sla_reporter", "product", "Report SLA compliance for all service commitments"),
    ("jnr_prod_forecast_reporter", "product", "Generate monthly revenue and user growth forecasts"),
    ("jnr_prod_kpi_dashboard", "product", "Update executive KPI dashboard with latest metrics"),
    ("jnr_rev_lead_scorer", "revenue", "Score inbound leads by fit and intent signals"),
    ("jnr_rev_lead_enricher", "revenue", "Enrich lead records with company and contact data"),
    ("jnr_rev_outreach_writer", "revenue", "Write personalized outreach emails for qualified leads"),
    ("jnr_rev_follow_up", "revenue", "Write follow-up sequence emails for sales pipeline"),
    ("jnr_rev_proposal_writer", "revenue", "Draft enterprise subscription proposals"),
    ("jnr_rev_rfp_writer", "revenue", "Write RFP responses for enterprise procurement"),
    ("jnr_rev_case_study", "revenue", "Write customer case studies and success stories"),
    ("jnr_rev_testimonial", "revenue", "Request and format customer testimonials"),
    ("jnr_rev_roi_calculator", "revenue", "Build custom ROI models for enterprise prospects"),
    ("jnr_rev_objection_handler", "revenue", "Draft responses to common sales objections"),
    ("jnr_rev_demo_prep", "revenue", "Prepare demo scripts and talking points"),
    ("jnr_rev_deck_slide", "revenue", "Create sales deck slides for specific industries"),
    ("jnr_rev_contract_drafter", "revenue", "Draft initial MSA and order form for review"),
    ("jnr_rev_deal_closer", "revenue", "Draft closing sequence emails for stalled deals"),
    ("jnr_rev_win_loss", "revenue", "Conduct win/loss analysis on closed opportunities"),
    ("jnr_rev_competitive_card", "revenue", "Create competitive battle cards for sales team"),
    ("jnr_rev_pricing_modeler", "revenue", "Model custom pricing for non-standard deal structures"),
    ("jnr_rev_free_trial_nurture", "revenue", "Write nurture emails for free trial users"),
    ("jnr_rev_trial_analyzer", "revenue", "Analyze trial user behavior for conversion signals"),
    ("jnr_rev_upgrade_nudge", "revenue", "Design in-app upgrade nudge messages"),
    ("jnr_rev_churn_detector", "revenue", "Detect churn risk signals in product usage data"),
    ("jnr_rev_churn_email", "revenue", "Write win-back emails for churned customers"),
    ("jnr_rev_renewal_reminder", "revenue", "Write renewal reminder email sequences"),
    ("jnr_rev_qbr_prep", "revenue", "Prepare Quarterly Business Review decks for accounts"),
    ("jnr_rev_health_monitor", "revenue", "Monitor account health scores, flag at-risk accounts"),
    ("jnr_rev_expansion_signal", "revenue", "Identify expansion signals: heavy usage, new users"),
    ("jnr_rev_upsell_email", "revenue", "Write targeted upsell email campaigns"),
    ("jnr_rev_seat_expander", "revenue", "Identify accounts for seat expansion outreach"),
    ("jnr_rev_plan_upgrader", "revenue", "Design upgrade campaigns: Pro → Enterprise"),
    ("jnr_rev_referral_email", "revenue", "Write referral invitation emails for promoters"),
    ("jnr_rev_affiliate_setup", "revenue", "Set up affiliate tracking links and materials"),
    ("jnr_rev_partner_email", "revenue", "Write partner onboarding and activation emails"),
    ("jnr_rev_blog_writer", "revenue", "Write SEO-optimized regulatory content blog posts"),
    ("jnr_rev_social_post", "revenue", "Write LinkedIn and Twitter content for regulatory topics"),
    ("jnr_rev_newsletter_writer", "revenue", "Write external newsletter: regulatory roundup"),
    ("jnr_rev_report_writer", "revenue", "Write free thought leadership reports for lead gen"),
    ("jnr_rev_webinar_copy", "revenue", "Write webinar invitations and follow-up emails"),
    ("jnr_rev_landing_copy", "revenue", "Write landing page copy for campaign-specific pages"),
    ("jnr_rev_ad_copy", "revenue", "Write Google and LinkedIn ad copy variations"),
    ("jnr_rev_retargeting", "revenue", "Design retargeting ad copy and audience segments"),
    ("jnr_rev_keyword_writer", "revenue", "Write SEO content targeting high-value keywords"),
    ("jnr_rev_backlink_outreach", "revenue", "Write backlink outreach emails to regulatory sites"),
    ("jnr_rev_podcast_pitch", "revenue", "Write podcast pitch emails for thought leadership"),
    ("jnr_rev_press_release", "revenue", "Write press releases for product launches"),
    ("jnr_rev_award_submitter", "revenue", "Write award submission applications"),
    ("jnr_rev_conf_abstract", "revenue", "Write conference talk abstract submissions"),
    ("jnr_rev_media_pitch", "revenue", "Write media pitches to fintech/regtech journalists"),
    ("jnr_rev_stripe_analyst", "revenue", "Analyze Stripe data: MRR movements, churn cohorts"),
    ("jnr_rev_invoice_gen", "revenue", "Generate invoice summaries for enterprise accounts"),
    ("jnr_rev_discount_approver", "revenue", "Apply discount approval workflow for deals"),
    ("jnr_rev_mrr_tracker", "revenue", "Track MRR movements: new, expansion, churn, reactivation"),
    ("jnr_rev_ltv_calculator", "revenue", "Calculate customer LTV by segment and plan"),
    ("jnr_rev_payback_calc", "revenue", "Calculate CAC payback period by acquisition channel"),
    ("jnr_rev_revenue_forecast", "revenue", "Build monthly revenue forecast from pipeline data"),
    ("jnr_rev_quota_tracker", "revenue", "Track sales quota attainment by rep/team"),
    ("jnr_rev_commission_calc", "revenue", "Calculate commission payouts from closed deals"),
    ("jnr_rev_crm_updater", "revenue", "Update CRM records with latest deal status and notes"),
    ("jnr_rev_pipeline_reporter", "revenue", "Generate weekly pipeline health reports"),
    ("jnr_rev_board_reporter", "revenue", "Draft revenue slides for board/investor reporting"),
    ("jnr_rev_pricing_analyst2", "revenue", "Analyze pricing page conversion rate by plan"),
    ("jnr_rev_trial_converter2", "revenue", "A/B test trial-to-paid upgrade messaging"),
    ("jnr_rev_notification_writer", "revenue", "Write behavioral notification copy for engagement"),
    ("jnr_rev_persona_targeter", "revenue", "Write persona-specific marketing copy"),
    ("jnr_rev_segment_writer", "revenue", "Write segment-specific email nurture sequences"),
    ("jnr_rev_onboard_emailer", "revenue", "Write day 1-30 onboarding email sequences"),
    ("jnr_rev_milestone_emailer", "revenue", "Write milestone-triggered emails (first alert, etc.)"),
    ("jnr_rev_dormant_reactivator", "revenue", "Write reactivation campaigns for dormant users"),
    ("jnr_rev_discount_emailer", "revenue", "Write time-limited discount campaign emails"),
    ("jnr_rev_season_campaigner", "revenue", "Write seasonal/annual regulatory event campaigns"),
    ("jnr_rev_compliance_calendar", "revenue", "Publish annual compliance calendar for lead gen"),
    ("jnr_rev_industry_report", "revenue", "Write industry vertical regulatory reports for leads"),
    ("jnr_rev_benchmark_report", "revenue", "Write benchmark reports for sales enablement"),
    ("jnr_rev_geo_campaigner", "revenue", "Write geo-targeted campaigns for key markets"),
    ("jnr_rev_segment_campaigner", "revenue", "Write segment-specific acquisition campaigns"),
    ("jnr_rev_trial_activation", "revenue", "Improve trial activation with personalized first steps"),
    ("jnr_rev_chat_bot_writer", "revenue", "Write chatbot conversation flows for sales qualification"),
    ("jnr_risk_gdpr_checker", "risk", "Check new features for GDPR compliance requirements"),
    ("jnr_risk_privacy_noter", "risk", "Document privacy implications of new data collection"),
    ("jnr_risk_consent_mgr", "risk", "Manage user consent flows and preference centers"),
    ("jnr_risk_erasure_handler", "risk", "Handle user right-to-erasure requests"),
    ("jnr_risk_portability_handler", "risk", "Handle user data portability requests"),
    ("jnr_risk_breach_reporter", "risk", "Document data breaches for regulatory reporting"),
    ("jnr_risk_dsar_handler", "risk", "Handle data subject access requests within 30 days"),
    ("jnr_risk_cookie_auditor", "risk", "Audit cookie consent banners and tracking compliance"),
    ("jnr_risk_dpa_register", "risk", "Maintain data processing activity register (GDPR Art. 30)"),
    ("jnr_risk_retention_enforcer", "risk", "Enforce data retention policies, delete expired data"),
    ("jnr_risk_contract_reviewer", "risk", "Review vendor data processing agreements"),
    ("jnr_risk_tos_updater", "risk", "Update terms of service when regulations change"),
    ("jnr_risk_pp_updater", "risk", "Update privacy policy for new data processing activities"),
    ("jnr_risk_dpa_writer", "risk", "Write DPAs for new data processor relationships"),
    ("jnr_risk_license_checker", "risk", "Check all OSS dependencies for license compatibility"),
    ("jnr_risk_copyright_checker", "risk", "Check content for copyright issues before publication"),
    ("jnr_risk_trademark_watcher", "risk", "Monitor for trademark infringement of RegWatch brand"),
    ("jnr_risk_patent_watcher", "risk", "Monitor patent landscape for FTO concerns"),
    ("jnr_risk_nda_manager", "risk", "Manage NDA signing workflows for enterprise sales"),
    ("jnr_risk_contract_logger", "risk", "Log all executed contracts in contract management system"),
    ("jnr_risk_ai_output_reviewer", "risk", "Review AI agent outputs for harmful or biased content"),
    ("jnr_risk_bias_sampler", "risk", "Sample AI outputs for bias analysis across jurisdictions"),
    ("jnr_risk_accuracy_checker", "risk", "Fact-check AI regulatory summaries against sources"),
    ("jnr_risk_hallucination_detector", "risk", "Detect AI hallucinations in regulatory content"),
    ("jnr_risk_confidence_auditor", "risk", "Audit agent confidence scores for calibration"),
    ("jnr_risk_escalation_reviewer", "risk", "Review all escalated tasks for pattern identification"),
    ("jnr_risk_decision_logger", "risk", "Log all material AI decisions with full reasoning trace"),
    ("jnr_risk_audit_trail", "risk", "Maintain immutable audit trail for all agent actions"),
    ("jnr_risk_trace_reviewer", "risk", "Review decision traces for compliance with policies"),
    ("jnr_risk_model_card", "risk", "Maintain model cards for all AI agents in production"),
    ("jnr_risk_incident_logger", "risk", "Log all security and privacy incidents"),
    ("jnr_risk_vuln_tracker", "risk", "Track open vulnerabilities from security scans"),
    ("jnr_risk_patch_verifier", "risk", "Verify security patches are applied and effective"),
    ("jnr_risk_access_auditor", "risk", "Audit user access rights, remove stale permissions"),
    ("jnr_risk_mfa_enforcer", "risk", "Monitor and enforce MFA adoption for all admin users"),
    ("jnr_risk_password_auditor", "risk", "Audit password policies and enforce complexity"),
    ("jnr_risk_api_key_auditor", "risk", "Audit API key usage, revoke unused keys"),
    ("jnr_risk_phishing_trainer", "risk", "Run anti-phishing awareness training"),
    ("jnr_risk_social_eng_monitor", "risk", "Monitor for social engineering attempts on staff"),
    ("jnr_risk_backup_validator", "risk", "Validate backup and recovery procedures"),
    ("jnr_risk_fraud_rule_writer", "risk", "Write fraud detection rules for payment processing"),
    ("jnr_risk_dispute_writer", "risk", "Write dispute responses for chargebacks and claims"),
    ("jnr_risk_aml_screener", "risk", "Screen enterprise customers against sanctions lists"),
    ("jnr_risk_kyb_processor", "risk", "Process Know Your Business verification for enterprises"),
    ("jnr_risk_abuse_report", "risk", "Generate abuse pattern reports for trust & safety"),
    ("jnr_risk_spam_detector", "risk", "Detect spam account creation and registration abuse"),
    ("jnr_risk_rate_limit_analyst", "risk", "Analyze rate limit violations for abuse patterns"),
    ("jnr_risk_scraping_blocker", "risk", "Identify and block unauthorized data scraping"),
    ("jnr_risk_account_sharer", "risk", "Detect account sharing violations in Enterprise plans"),
    ("jnr_risk_bot_detector", "risk", "Detect bot traffic in API and web analytics"),
    ("jnr_risk_financial_recon", "risk", "Reconcile Stripe payments against database records"),
    ("jnr_risk_tax_reporter", "risk", "Generate tax reporting data for subscription revenue"),
    ("jnr_risk_vat_handler", "risk", "Handle EU VAT/GST calculation and reporting"),
    ("jnr_risk_currency_reporter", "risk", "Report revenue split by currency and jurisdiction"),
    ("jnr_risk_refund_processor", "risk", "Process refund requests within policy guidelines"),
    ("jnr_risk_soc2_documenter", "risk", "Document SOC2 evidence for annual audit"),
    ("jnr_risk_iso_documenter", "risk", "Document ISO 27001 controls and evidence"),
    ("jnr_risk_pen_test_retest", "risk", "Re-test fixed vulnerabilities from pen test findings"),
    ("jnr_risk_vendor_questioner", "risk", "Complete vendor security questionnaires"),
    ("jnr_risk_nist_mapper", "risk", "Map controls to NIST CSF and report coverage"),
    ("jnr_risk_risk_register", "risk", "Maintain enterprise risk register with status updates"),
    ("jnr_risk_bcp_tester", "risk", "Test business continuity plan annually"),
    ("jnr_risk_dr_tester", "risk", "Test disaster recovery procedures, log results"),
    ("jnr_risk_crisis_communicator", "risk", "Draft crisis communication for material incidents"),
    ("jnr_risk_regulator_notifier", "risk", "Draft notifications to regulators when required"),
    ("jnr_risk_employee_nda", "risk", "Manage employee NDA and IP assignment agreements"),
    ("jnr_risk_board_reporter2", "risk", "Draft board risk report slides quarterly"),
    ("jnr_risk_esg_reporter", "risk", "Report ESG metrics for enterprise customer reporting"),
    ("jnr_risk_carbon_tracker", "risk", "Track and report cloud carbon footprint"),
    ("jnr_risk_diversity_reporter", "risk", "Report workforce diversity metrics"),
    ("jnr_risk_whistleblower", "risk", "Manage whistleblower reporting channel"),
    ("jnr_risk_ethics_hotline", "risk", "Monitor ethics hotline submissions and triage"),
    ("jnr_risk_conflict_checker", "risk", "Check for conflicts of interest in partnerships"),
    ("jnr_risk_gift_policy", "risk", "Enforce gift and entertainment policy"),
    ("jnr_risk_policy_updater", "risk", "Update internal policies when regulations change"),
    ("jnr_risk_training_tracker", "risk", "Track compliance training completion rates"),
]

JUNIOR_REGISTRY: dict[str, type] = {
    type_key: create_junior_class(type_key, dept, resp)
    for type_key, dept, resp in _JUNIOR_DEFINITIONS
}
print(f"Junior agents registered: {len(JUNIOR_REGISTRY)}")
